PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX gip_prop: <http://gipuzkoa.eus/prop/>
PREFIX drm:<http://vocab.data.gov/def/drm#>

SELECT ?museo ?kopurua ?nombre

WHERE {
    GRAPH <http://data.abd.ehu.eus/museoak> {
        ?museo rdf:type <http://dbpedia.org/ontology/museum> .
        ?museo gip_prop:kopurua ?kopurua .
        ?worker rdf:type foaf:person .
        ?worker foaf:name ?nombre .
        ?worker drm:worksFor ?museo .
        FILTER (?kopurua > "800"^^xsd:int) 
        FILTER(REGEX(?nombre,'Mi.*')) 
    }
}
